/* Simulation code for Events generated by the OpenModelica Compiler 1.9.0 Beta2 (r????). */
#define time data->localData[0]->timeValue

/* States */
#define _$Px(i) data->localData[i]->realVars[0]
#define $Px _$Px(0)
#define $P$PRE$Px data->simulationInfo.realVarsPre[0]
#define $P$ATTRIBUTE$Px data->modelData.realVarsData[0].attribute
#define $Px__varInfo data->modelData.realVarsData[0].info
#define $P$PRE$Px__varInfo data->modelData.realVarsData[0].info
/* StatesDerivatives */
#define _$P$DER$Px(i) data->localData[i]->realVars[1]
#define $P$DER$Px _$P$DER$Px(0)
#define $P$PRE$P$DER$Px data->simulationInfo.realVarsPre[1]
#define $P$ATTRIBUTE$P$DER$Px data->modelData.realVarsData[1].attribute
#define $P$DER$Px__varInfo data->modelData.realVarsData[1].info
#define $P$PRE$P$DER$Px__varInfo data->modelData.realVarsData[1].info
/* Algebraic Vars */
#define _$Pz(i) data->localData[i]->realVars[2]
#define $Pz _$Pz(0)
#define $P$PRE$Pz data->simulationInfo.realVarsPre[2]
#define $P$ATTRIBUTE$Pz data->modelData.realVarsData[2].attribute
#define $Pz__varInfo data->modelData.realVarsData[2].info
#define $P$PRE$Pz__varInfo data->modelData.realVarsData[2].info
/* Algebraic Parameter */
#define $Pk data->simulationInfo.realParameter[0]
#define _$Pk(i) $Pk
#define $P$ATTRIBUTE$Pk data->modelData.realParameterData[0].attribute
#define $Pk__varInfo data->modelData.realParameterData[0].info
/* External Objects */
/* Algebraic Integer Vars */
/* Algebraic Integer Parameter */
/* Algebraic Boolean Vars */
/* Algebraic Boolean Parameters */
/* Algebraic String Variables */
/* Algebraic String Parameter */
/* Jacobian Variables */
/* G */
/* G sparse indexes */

/* A */
#define $Px$pDERA$Px data->simulationInfo.analyticJacobians[1].seedVars[0]
#define $Px$pDERA$Px__varInfo dummyVAR_INFO
/* A sparse indexes */
#define $Px$pDERA$indexdiff 0
#define $Px$pDERA$indexdiffed 0
/* B */
/* B sparse indexes */

/* C */
/* C sparse indexes */

/* D */
/* D sparse indexes */

