CC=gcc
CPP=g++

MACROS=-DBUILD_FMI_DLL
OPTFLAGS=-O3
CFLAGS=$(MACROS) -march=x86-64 -fPIC
INCLUDE=-I.

all:	clean step_t0.fmu

step_t0.fmu:	step_t0.so
	mkdir -p step_t0/binaries/linux64
	cp step_t0.so step_t0/binaries/linux64
	cp modelDescription.xml step_t0
	cd step_t0 && zip ../step_t0.fmu -r *
	rm -r step_t0

step_t0.so:	step_t0.o
	$(CC) -shared  $(OPTFLAGS) $(CFLAGS) -o step_t0.so step_t0.o

step_t0.o:	step_t0.c
	$(CC) $(INCLUDE) -c $(OPTFLAGS) $(CFLAGS) -o step_t0.o step_t0.c

clean:
	rm -f step_t0.fmu step_t0.so step_t0.o
