CC=gcc
CPP=g++

MACROS=-DBUILD_FMI_DLL
OPTFLAGS=-O3
CFLAGS=$(MACROS) -march=x86-64 -fPIC
INCLUDE=-I.

all:	clean zigzag.fmu

zigzag.fmu:	zigzag.dylib
	mkdir -p zigzag/binaries/darwin64
	cp zigzag.dylib zigzag/binaries/darwin64
	cp modelDescription.xml zigzag
	cd zigzag && zip ../zigzag.fmu -r *
	rm -r zigzag

zigzag.dylib:	zigzag.o
	$(CC) -dynamiclib  $(OPTFLAGS) $(CFLAGS) -o zigzag.dylib zigzag.o

zigzag.o:	zigzag.c
	$(CC) $(INCLUDE) -c $(OPTFLAGS) $(CFLAGS) -o zigzag.o zigzag.c

clean:
	rm -f zigzag.fmu zigzag.so zigzag.o
